name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [7.2, 7.3, 7.4, 8.0, 8.1]
        stability: [prefer-stable]
        include:
          - php: 7.2
            stability: prefer-lowest
            os: ubuntu-latest

    name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pcntl, shmop, sysvmsg
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit

  phpstan:
    runs-on: ubuntu-latest
    name: Run phpstan analyse
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: pcntl, shmop, sysvmsg
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction

      - name: Execute phpstan analyse
        run: vendor/bin/phpstan analyse --memory-limit 1G
